### ISSUE TITLE
Compare View: information on what metrics means

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#10]
User feedback has shown most do not know what our metrics represent / are measuring, i.e. "fnbpaint" 
This information should be presented in the UI in a concise way, without having to link to external documentation

**Comment by cybraia** [comment]
Hi, @kimberlythegeek  @Carla-Moz I would like to work on this. Could you give me more details about fubpaint? Let me know where the UI has to be changed. Thanks!
