### ISSUE TITLE
Generate Permalinks

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#12]
Generate permalinks/short links for users to share/save comparison results

**Comment by cybraia** [comment]
Hi,I would like to work on this. Could you please give me more details? Thanks!

**Comment by cybraia** [comment]
@kimberlythegeek could you please give a short description about this? Thanks

**Comment by kimberlythegeek** [comment]
this will be moved to our internal issue tracker, as it requires a higher lever of security clearance.
