### ISSUE TITLE
add file-loader to handle SVG files and remove fileTransformer.js 

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#125]
from Nazim:
it looks like we are only using this fileTransformer for svg files. During webpack compilation, we can tell the webpack how to load a certain file type. For svg files, we can tell the webpack to load it as a "file" with a "file-loader". Here's how we are doing it on profiler codebase: https://github.com/firefox-devtools/profiler/blob/fe13f1f5e9d2205b2b6bde46d3080e7be3d277e0/webpack.config.js#L65-L68 This is the documentation for the loader: https://v4.webpack.js.org/loaders/file-loader/ when you add this loader, you won't have to have this transform, so you can remove it from package.json as well

**Comment by anna-kulyk** [comment]
@kimberlythegeek hi, I am outreachy applicant and would like to be assigned to this issue

**Comment by anna-kulyk** [comment]
@kimberlythegeek @Carla-Moz 

unfortunately installing file-loader doesn't help with jest, it fails with this error:

`       SyntaxError: Unexpected token '<'`

       8 | import osx from './img/osx.svg';
       9 | import windows from './img/windows.svg';
    > 10 | import zap from './img/zap-10.svg';
         |                                    ^
      11 |
      12 | const components = {
      13 |   MuiButton: {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1796:14)
      at Object.<anonymous> (src/theme/components.js:10:58)

I did a little research and as far as I can tell, the only way to remove fileTransformer.js is to install jest-transformer-svg, but it basically does the same thing as fileTransformer.
