### ISSUE TITLE
restructure hooks directory and group by type

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#126]
from Nazim:

Not for this PR, and not sure if you've talked about this before. But I feel like this hooks directory will be pretty crowded in the future when we keep adding new hooks to the codebase. I wonder if we can make that a bit better by grouping the related hooks together. Like with a similar structure to the components directory. What do you think?

**Comment by okerekechinweotito** [comment]
@kimberlythegeek  please assign this issue to me

**Comment by kelani34** [comment]
HI @kimberlythegeek  I'm an outreachy applicant Can I get this issue assigned to me?
