### ISSUE TITLE
consider using Sets instead of arrays 

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#137]
consider replacing the `checked` array, possible the revisions arrays (`searchResults` and `selectedRevisions`) with sets instead: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set#constructor

**Comment by mohammadareeb95** [comment]
Hey @kimberlythegeek 
Can I work on this issue?

**Comment by siddhi-244** [comment]
Hello, I am a outreachy participant,  can I work on this?

**Comment by S1Y333** [comment]
Hi Kimberly, my name is Sylvia and I am a outreachy participant, can I try this one? Thank you

**Comment by siddhi-244** [comment]
> Got the issue! Can you give me a little more context in which files i have to make the changes ?

**Comment by Safei-Ashraf** [comment]
@kimberlythegeek  can I be assigned to this too?

**Comment by S1Y333** [comment]
@siddhi-244 Nice to meet you, I am also a outreachy participant, are you able to send Kimberly messages in the Element App? I am new to contributing open-source projects and have a lot of questions but don't know where I can get help :(. Do you have any clue? Thank you so much

**Comment by Ayesha-Solanki15** [comment]
hey, @kimberlythegeek , I wanna work on this, can you assign it to me as well?

**Comment by S1Y333** [comment]
@Carla-Moz 

Can you please give us some clues about which array is the one we need to change? Also, if possible, can you please introduce briefly the logic of the whole project? That would be very helpful. Thanks so much!

<img width="370" alt="Screen Shot 2023-03-07 at 2 24 55 PM" src="https://user-images.githubusercontent.com/105386341/223530235-38a31057-391a-450c-8b58-59e680e910e5.png">

<img width="387" alt="Screen Shot 2023-03-07 at 2 24 20 PM" src="https://user-images.githubusercontent.com/105386341/223530049-1cd9fef2-3ce1-45f1-b8e7-8260400a958b.png">

**Comment by ipriyanshi1708** [comment]
Hi @kimberlythegeek, I am an outreachy applicant and a frontend developer. Can you please give me a chance to give it a try.

Thanks!

**Comment by Avi-88** [comment]
Hi @kimberlythegeek @Carla-Moz , could you please assign me this issue as well, thanks

**Comment by taofeeqhamzat** [comment]
There might be trade-offs to worry about when adding Set objects to the store state
https://redux.js.org/faq/organizing-state#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state
