### ISSUE TITLE
search results list items re-render everytime an item is checked/unchecked

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#140]

**Comment by julienw** [comment]
Copying my comment here for easier reference:

> I digged deeper to understand what's going on. And I think I found the issue: inside `useCheckRevision` we're using a `useSelector` that returns the full `revisions` object, which changes when we click only one. Because the `SearchResultsList` uses `useCheckRevision`, then it rerenders when the array changes.

> I'm not sure what the best solution to this is. `handleToggle` needs `checkRevisions` to do its checks. But ideally we don't want `checkRevisions` to retrigger a render. This adds to the idea that I still think the code in `handleToggle` isn't at the best place. Maybe it could be a thunk action instead (because thunk actions can get the state)?

**Comment by betty-alagwu** [comment]
hello @kimberlythegeek i already sent a message in the forum. 
i will love to work on this issue

**Comment by Formasitchijoh** [comment]
Hello @kimberlythegeek i would like to work on this issue can you give me a chance

**Comment by betty-alagwu** [comment]
Working on it

**Comment by Formasitchijoh** [comment]
> Copying my comment here for easier reference:
> 
> > I digged deeper to understand what's going on. And I think I found the issue: inside `useCheckRevision` we're using a `useSelector` that returns the full `revisions` object, which changes when we click only one. Because the `SearchResultsList` uses `useCheckRevision`, then it rerenders when the array changes.
> > I'm not sure what the best solution to this is. `handleToggle` needs `checkRevisions` to do its checks. But ideally we don't want `checkRevisions` to retrigger a render. This adds to the idea that I still think the code in `handleToggle` isn't at the best place. Maybe it could be a thunk action instead (because thunk actions can get the state)?

@julienw @kimberlythegeek 
I was going through the codebase to identify the issue and i just want to enquire something does the checkRevisions array  in useCheckRevision contain the entire revision of a particular repository or the checked revisions

**Comment by Formasitchijoh** [comment]
> Copying my comment here for easier reference:
> 
> > I digged deeper to understand what's going on. And I think I found the issue: inside `useCheckRevision` we're using a `useSelector` that returns the full `revisions` object, which changes when we click only one. Because the `SearchResultsList` uses `useCheckRevision`, then it rerenders when the array changes.
> > I'm not sure what the best solution to this is. `handleToggle` needs `checkRevisions` to do its checks. But ideally we don't want `checkRevisions` to retrigger a render. This adds to the idea that I still think the code in `handleToggle` isn't at the best place. Maybe it could be a thunk action instead (because thunk actions can get the state)?

@julienw @kimberlythegeek 
I was going through the codebase to identify the issue and i just want to enquire something does the checkRevisions array  in useCheckRevision contain the entire revision of a particular repository or the checked revisions

**Comment by Ayesha-Solanki15** [comment]
@kimberlythegeek, can you assign it to me as well?

**Comment by Formasitchijoh** [comment]
@Carla-Moz @kimberlythegeek  please can you checkout out my PR on #310
