### ISSUE TITLE
remove State type and replace references to it with RootState

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#156]
originally we were typing State explicitly, but have since added `RootState` which infers the type of state.

**Comment by kimberlythegeek** [comment]
see https://github.com/mozilla/perfcompare/pull/149#discussion_r899232988

**Comment by kelani34** [comment]
Hi @kimberlythegeek I'm an outreachy applicant I'd love to work on this

**Comment by emmaz12** [comment]
Hi @kimberlythegeek I would like to give this a shot!
