### ISSUE TITLE
make icons look "hoverable"

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#159]
ensure any item that has a tooltip has affordances to indicate to the user they can be hovered

**Comment by kimberlythegeek** [comment]
[Affordances and signifiers](https://medium.com/@h_locke/affordances-and-signifiers-82bd6f50fc1a)

[How can I make it obvious that a page element is to be hovered over?](https://ux.stackexchange.com/questions/13706/how-can-i-make-it-obvious-that-a-page-element-is-to-be-hovered-over)

**Comment by Trish-P** [comment]
Hi Kimberly, can I be assigned to this?

**Comment by iamatifmoin** [comment]
@kimberlythegeek I'd love to work on this please.

**Comment by Gathu17** [comment]
@kimberlythegeek I would also like to work on this

**Comment by vinayakjaas** [comment]
hii @kimberlythegeek please assign this task to me

**Comment by Businge931** [comment]
Hi @kimberlythegeek can I work on this

**Comment by timmy3000** [comment]
Hello @kimberlythegeek

My name is Hatim Matsue and i am Outreachy participant.
May i please work on this issue?

Thank you.

**Comment by tobidosumu** [comment]
Hello @kimberlythegeek 

It will be my pleasure to jump in on this one if you don't mind.
May I request you assign this task to me?
Thank you.
