### ISSUE TITLE
Update header component to match new design

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#168]

**Comment by mohammadareeb95** [comment]
@kimberlythegeek Can I try working on this?

**Comment by kimberlythegeek** [comment]
Hi there! Thank you for your interest in contributing. We have recently finished a new UX design, so unfortunately this issue is no longer valid, as the CSS will be replaced to match the new design.

I will replace this issue to be 'Update header component' to match the latest design: 
![image](https://user-images.githubusercontent.com/18633586/223188155-40680c0c-40dd-4d49-88e1-b0237612b9ee.png)

**Comment by kimberlythegeek** [comment]
requirements:

- [ ] update dark mode design

- [ ] header text is smaller, add description below

- [ ] add 'learn more' button, which for now does not link to anything

- [ ] update background for header component (I will get the image for background and share this

let me know if you are still interested, thanks!

**Comment by Sally-N** [comment]
@kimberlythegeek I am an outreachy applicant, can i work on this??

**Comment by luquiceno** [comment]
Hi @kimberlythegeek,  I'm an Outreachy applicant. Is possible also to work on this issue?

**Comment by kimberlythegeek** [comment]
![image](https://user-images.githubusercontent.com/18633586/223226187-83621473-af10-4f7b-a7b9-564378b55c9e.png)
![image](https://user-images.githubusercontent.com/18633586/223226230-af04704e-8412-4ac1-a510-2e04a0e8ca37.png)

**Comment by kimberlythegeek** [comment]
they may seem to be the same (I had to run an image diff to be sure, hah :sweat_smile: but they are slightly different) the first is the dark mode image, the second is light mode

**Comment by tessa5** [comment]
Hello, @kimberlythegeek I am an outreachy applicant. Please assign me to this repo. Thank you.

**Comment by Sally-N** [comment]
@kimberlythegeek Thanks for assigning me. working on it

**Comment by luquiceno** [comment]
Thanks @kimberlythegeek

**Comment by adevicky** [comment]
I'm an outreachy applicant, please can i work on this too?

**Comment by adevicky** [comment]
I'm an outreachy applicant, please can i work on this too?

**Comment by ipriyanshi1708** [comment]
I am an Outreachy applicant, I would love to contribute to this issue. Please assign it to me.

Thanks!

**Comment by luquiceno** [comment]
Hi @kimberlythegeek. This is an update. I'm still working on this, I've already made some changes according to the requirements. But for some other I'm understanding the code better.

**Comment by codeinvoke7** [comment]
@kimberlythegeek Please can I work on this..??

**Comment by luquiceno** [comment]
Hi @kimberlythegeek I just sent a pull request. I think I already have all the requirements you mentioned, but feel free to give me any feedback. I would be happy to change the code or add additional things you consider necessary.

**Comment by luquiceno** [comment]
Hi @Carla-Moz and @kimberlythegeek by mistake I change the state of my pull request to "CLOSE" and I didn't want. Can you reopen it? Thanks a lot.

**Comment by luquiceno** [comment]
Hi @kimberlythegeek and @Carla-Moz, this is a new [pull request](https://github.com/mozilla/perfcompare/pull/452) that I created because trying to resolve the conflicts in the first pull request, I accidentally close it. I hope this doesn't create to much confusion for you. Apologies.
