### ISSUE TITLE
Add warning message when comparing builds from different projects

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#169]
This may be done in the Snackbar alert, or a message displayed above or below the selected revisions table. Needs discussion

**Comment by Jojowangfy** [comment]
Hi Kimberly, may I give this a try? @kimberlythegeek

**Comment by sabbCodes** [comment]
Hi @kimberlythegeek, I'd like to give this a try please.

**Comment by tessa5** [comment]
Hey @kimberlythegeek, I would like to contribute to this please.

**Comment by ipriyanshi1708** [comment]
Hii @kimberlythegeek , I am an outreachy applicant, I would like to give it a try. Can you please assign it to me?

Thanks!

**Comment by sabbCodes** [comment]
Added warning when comparing different revisions from different repositories. https://github.com/mozilla/perfcompare/pull/368

**Comment by Jojowangfy** [comment]
Hi @kimberlythegeek , I've added the feature but I'm not really good at writing test. So sorry for that. It's in #447
