### ISSUE TITLE
Change page title based on route

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#171]
Currently all page titles are "PerfCompare", so when using the back button, the history is not descriptive of the page/view.

**Comment by Biki-das** [comment]
@kimberlythegeek would like to give this a try

**Comment by Formasitchijoh** [comment]
@kimberlythegeek  would like to work on this issue can you give me chance

**Comment by Biki-das** [comment]
> @kimberlythegeek would like to work on this issue can you give me chance

sorry @Formasitchijoh i am working on this , in the meanwhile you can look for other issues! dont worry more issues will be created soon :-)

**Comment by Formasitchijoh** [comment]
well  we could collaborate on it so i can keep myself busy and also learn from you if you don't mind

**Comment by Ayesha-Solanki15** [comment]
@kimberlythegeek, I would like to work on this.

**Comment by ipriyanshi1708** [comment]
I would like to contribute on this issue. Please assign it to me.

Thanks!

**Comment by Gathu17** [comment]
I would like to contribute on this

**Comment by Carla-Moz** [comment]
> 

More than one applicant can work on an issue. It's fine.

**Comment by Avi-88** [comment]
> > 
> 
> More than one applicant can work on an issue. It's fine.

@Carla-Moz If possible please assign this issue to me as well , thanks

**Comment by Formasitchijoh** [comment]
@kimberlythegeek  @Carla-Moz  I think this issue has already been solved 
check out the gif
[Screencast from 03-13-2023 05:40:29 PM.webm](https://user-images.githubusercontent.com/76694292/224768894-84f59f33-d4da-40f5-8aee-da7a66245134.webm)

**Comment by Formasitchijoh** [comment]
if theres any modifications to be made i  would like to continue working on it thank you

**Comment by mayangiaretha** [comment]
Hey @kimberlythegeek Hoping to be assigned to this issue. Resolved it last week under PR #343
