### ISSUE TITLE
investigate optimization for production build

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#213]
there are various options for optimization a build using webpack. one of these is code splitting, which I experimented with and was able to reduce the size of the main bundle file

https://webpack.js.org/configuration/optimization/

**Comment by KOKUMUbooker** [comment]
Hello , I'm an Outreachy applicant, I'd love to work on this

**Comment by priyasarpate** [comment]
Hi @kimberlythegeek,

I am an Outreachy applicant, would love to work on this!

**Comment by Formasitchijoh** [comment]
@Carla-Moz  please assign me this issue, I am already working on it
