### ISSUE TITLE
resolve 'axe is already running' issue

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#222]
When I added an additional accessibility test for compare view in dark mode, I began getting errors on both Compare View tests: `thrown: "Axe is already running. Use `await axe.run()` to wait for the previous run to finish before starting a new run."`

I tried resolving this but have not yet found a solution. For now I have commented out this test until a solution is found.

**Comment by kimberlythegeek** [comment]
Great! let me know if you have any questions. You can also connect with us in our element chat: https://matrix.to/#/#perfcompare:mozilla.org

**Comment by Safei-Ashraf** [comment]
@kimberlythegeek  can I work on this too?

**Comment by oburasamuel** [comment]
I think we should start from here.

**Comment by Biki-das** [comment]
@vinayakjaas working on it, seems like we have the problem with the current jes-axe version upgrading it seems to solve the issue!
