### ISSUE TITLE
fix width of edit revision popover

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#225]
1. click input on search page
2. select two recent revisions and click `+` button 
3. click `compare`
4. on the results view, click the edit button (looks like a pencil) next to one of the revisions
5. the search popover is not the same length as the selected revisions table

**Comment by cybraia** [comment]
Hi Kimberly, I would like to work on this. Can you please give some more details about it?

**Comment by sabbCodes** [comment]
Hello, I would love to try this out. But, the description is missing.

**Comment by kimberlythegeek** [comment]
@cybraia great, thanks! 

@sabbCodes FYI you can still work on this issue, despite it being assigned to Krishna. This can be a valuable way to compare applicants. It would help to send me a private message (@kimberlythegeek on https://chat.mozilla.org/#/login) so that I can better keep track of applicants and the issues they are working on.

**Comment by kimberlythegeek** [comment]
1. click input on search page
2. select two recent revisions and click `+` button 
3. click `compare`
4. on the results view, click the edit button (looks like a pencil) next to one of the revisions
5. the search popover is not the same length as the selected revisions table

**Comment by kimberlythegeek** [comment]
@cybraia @sabbCodes FYI, all new PRs should be submitted to the `beta` branch, not `staging`. it should do this by default.

Thanks!

**Comment by okerekechinweotito** [comment]
...Also working on this

**Comment by vinayakjaas** [comment]
Hii, Please assign  this task to me I try to solve this bugs

**Comment by Businge931** [comment]
Hi @kimberlythegeek, I wanna work on this bug also. Kindly assign me to it
