### ISSUE TITLE
checked revision is not cleared after editing selected revision in compare results view

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#226]

**Comment by beatrice-acasandrei** [comment]
@kimberlythegeek Is this still reproducing? Could you add some steps to reproduce?

**Comment by kimberlythegeek** [comment]
yes, it is. 

STR:
1) add two revisions 
2) click "compare'
3) on results page, click edit button
4) focus search input
5) check a result and click `+` add button
6) click edit button again, and focus input

previously checked result is still checked

**Comment by Formasitchijoh** [comment]
@kimberlythegeek  could i work on this please

**Comment by tessa5** [comment]
Hi, @kimberlythegeek please assign this to me too please.

**Comment by vinayakjaas** [comment]
Hii ,Please assign this task to me I try to solve this issue

**Comment by OndigoWendy** [comment]
Hi @kimberlythegeek @Carla-Moz 
Kindly check out my PR on this issue https://github.com/mozilla/perfcompare/pull/345

**Comment by Businge931** [comment]
Assign me to this issue please
