### ISSUE TITLE
PerfCompare header underline resizes based on window size

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#257]
The underline should stay the same regardless of window size

**Comment by kimberlythegeek** [comment]
Of course 😊

Thanks for your interest in contributing!

**Comment by GPain2007** [comment]
Yes I am. Still working on this.

**Comment by kimberlythegeek** [comment]
cool, thanks! let us know if you need anything from us.

**Comment by GPain2007** [comment]
Will do!

**Comment by GPain2007** [comment]
<img width="1512" alt="Screen Shot 2022-11-08 at 7 55 06 PM" src="https://user-images.githubusercontent.com/97716889/200717936-bdcb9faa-16f9-4a99-89c4-095903f3ed00.png">

**Comment by GPain2007** [comment]
<img width="1512" alt="Screen Shot 2022-11-08 at 7 54 57 PM" src="https://user-images.githubusercontent.com/97716889/200717967-87ab95a9-aa31-4194-a459-39df8e875908.png">
<img width="1512" alt="Screen Shot 2022-11-08 at 7 54 50 PM" src="https://user-images.githubusercontent.com/97716889/200717979-672ee22c-2b3d-4c5e-afc8-3f5f7e2a3559.png">

**Comment by GPain2007** [comment]
I fixed the issue. Please let me know if this is what they want. If so i will push the code now. Also do i push to a branch?

**Comment by kimberlythegeek** [comment]
Please open a pull request to the `staging` branch and we will test and review it :) 

Thanks!

**Comment by kimberlythegeek** [comment]
fixed by #275
