### ISSUE TITLE
Confidence tooltip breaks UI

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#258]
when there is a result that has unknown confidence, the alignment of the cell is disrupted, and after several of these in the same table, the difference becomes very apparent:

![image](https://user-images.githubusercontent.com/18633586/195633725-acb06f01-79ae-4f32-a8eb-e0b957ee2e5b.png)

one suggestion would be to use SVG images directly and wrapping them in a `Tooltip` component, rather than wrapping the Table Cell, which seems to be where the issue arises.

When adding these icons originally, I encountered issues with using SVG images in typescript, which is why the background image approach was taken. Since ejecting and switching to webpack, this may no longer be an issue

**Comment by NikolaDojic** [comment]
The issue with the SVG is not completely resolved, and it could be dealt with in at least two different ways.
The current state of things is that we cannot import SVGs in the .tsx files in a way we normally would using plain js.
The reason for this is inside  [src/types/custom file](https://github.com/mozilla/perfcompare/blob/staging/src/types/custom.d.ts). There, we declared that the export of the SVG files is of `React.FunctionComponent<React.SVGAttributes<SVGElement>>`  type, when in fact, what we get by importing from the SVG file is data URI, in form of a string. 
To resolve this mismatch, we could either make a  fix in the `src/types/custom.d.ts` file or add some SVG loader to webpack or babel configuration, for example [@svgr/webpack](https://www.npmjs.com/package/@svgr/webpack). The loader would transform SVG file export to a react element for us.
The question is, what would be a preferred way of dealing with SVGs?  
This could probably be a separate issue, but maybe it would not hurt to resolve this more general problem first, to avoid refactoring.

**Comment by mohammadareeb95** [comment]
Hey! Can I work towards submitting a PR to this issue?

**Comment by Biki-das** [comment]
@kimberlythegeek i would like to work on this!

**Comment by anna-kulyk** [comment]
@kimberlythegeek would love to fix this issue

**Comment by Safei-Ashraf** [comment]
@kimberlythegeek  can I try to fix this?

**Comment by cherish2003** [comment]
@kimberlythegeek  i am outreachy applicant i would to love to work on this one can you assign me

**Comment by omondi8399** [comment]
@kimberlythegeek i would love to work on this , can i be assigned this  ?

**Comment by ipriyanshi1708** [comment]
Hii, I am an outreachy applicant. Please tell me that how can I reach this result ui because I am not able to reach this ui or this page. On clicking on compare button, I am getting a popup of error

**Comment by Bukolab99** [comment]
> Hii, I am an outreachy applicant. Please tell me that how can I reach this result ui because I am not able to reach this ui or this page. On clicking on compare button, I am getting a popup of error

Hi Ipriyanshi what was the first step you took trying to reach the result ui. If you're tring to work on this issue i'd advice you clone the repositorythen you locate the relevant files which is the src/types/custom.d.ts file and the file where you are attempting to import the SVG.
Next step is to Identify the specific issue: Review the error message or console output to determine the specific issue with the SVG import and then determine the cause of the issue. Review the code in the src/types/custom.d.ts file and the file where you are attempting to import the SVG to determine the cause of the issue. and finally decide on a solution. 
Hope that will get you started. Cheers

**Comment by ipriyanshi1708** [comment]
> > Hii, I am an outreachy applicant. Please tell me that how can I reach this result ui because I am not able to reach this ui or this page. On clicking on compare button, I am getting a popup of error
> 
> Hi Ipriyanshi what was the first step you took trying to reach the result ui. If you're tring to work on this issue i'd advice you clone the repositorythen you locate the relevant files which is the src/types/custom.d.ts file and the file where you are attempting to import the SVG. Next step is to Identify the specific issue: Review the error message or console output to determine the specific issue with the SVG import and then determine the cause of the issue. Review the code in the src/types/custom.d.ts file and the file where you are attempting to import the SVG to determine the cause of the issue. and finally decide on a solution. Hope that will get you started. Cheers

I am trying to see this ui as a user but I am not able to get the result in any case. I always got an error that No results found. So, Please help me to get to this so that I can understand the code base in a better way.

**Comment by tobidosumu** [comment]
@kimberlythegeek @Carla-Moz @anna-kulyk 
Hello.
Please I would love to fix this issue.
Kindly assign it to me as I have already fixed it (but I did not commit the fix) in another branch of a closely related [task](https://github.com/mozilla/perfcompare/pull/369)
