### ISSUE TITLE
Editing a revision from Compare View doesn't update results

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#262]
when editing a revision, the API is not called again, and the results remain the same

**Comment by GPain2007** [comment]
I would  like this issue to be assigned to me. Thank you

**Comment by kimberlythegeek** [comment]
Done :) 

Thanks!

**Comment by GPain2007** [comment]
Just checking to see if the patch you created fixed this issue?

I've been working on where the issue was and think I got it fixed but wanted to make sure. Sorry its taking me a long time with this one. I had to study and learn TypeScript and Redux.

**Comment by kimberlythegeek** [comment]
@GPain2007 which patch are you referring to? as far as I know there has not been a patch to resolve this yet

**Comment by beatrice-acasandrei** [comment]
@GPain2007 Are you currently working on this issue?

**Comment by GPain2007** [comment]
Yes I’m still working on this.

**Comment by mayangiaretha** [comment]
@kimberlythegeek , as per the gif below. This issue seems to have been resolved. Please advise.

![PerfCompare — Mozilla Firefox 2023-03-07 12-11-03](https://user-images.githubusercontent.com/101508815/223381797-0cfe3bb7-3ae7-47e0-8d3f-81fb8779e922.gif)
