### ISSUE TITLE
columns in results view are not a consistent width

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#267]
depending on the values in the tables, columns are of varying widths. ensure columns stay the same width

**Comment by Phyya** [comment]
Hi,
I am an outreachy applicant. Can I be assigned to this issue so that I can start working on it? Thanks.

**Comment by mayangiaretha** [comment]
Hey @kimberlythegeek, I am an outreachy applicant. If possible I would love to be assigned this issue or any other available issue, thanks.

**Comment by Safei-Ashraf** [comment]
@kimberlythegeek  Would love to give this a try

**Comment by siddhi-244** [comment]
Hello! I am an Outreachy applicant and would like to work on this issue !

**Comment by Ayesha-Solanki15** [comment]
@kimberlythegeek, I would like to try my hands on this.

**Comment by priyasarpate** [comment]
Hello @kimberlythegeek,

I would love to work on this!

**Comment by sumairq** [comment]
Hi @kimberlythegeek ,
I am an Outreachy applicant. I would love to be assigned to this issue so that I can apply my frontend-skills to make the columns a consistent width.

**Comment by Businge931** [comment]
Hi @kimberlythegeek please assign to this issue

**Comment by satyamksharma** [comment]
Hi @kimberlythegeek I would like to work on thus issue and request you to assign me to this issue. Thank you

**Comment by mayangiaretha** [comment]
Resolved in PR #319
