### ISSUE TITLE
Search input error does not disappear if results are retrieved after an error

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#268]
Steps to reproduce:

1. start typing a valid search term, such as an email
2. pause long enough for the timeout to call the fetch results method
3. continue typing the search term

Expected outcome: the input error would be cleared when resuming typing 
Actual outcome: the input error remains, even after results are retrieved

**Comment by kimberlythegeek** [comment]
This may have been resolved by a different patch, I am not seeing the error either.

**Comment by beatrice-acasandrei** [comment]
@kimberlythegeek Should we close this issue?
