### ISSUE TITLE
Outreachy HOW TO: Creating an issue asking for help

### ISSUE THREAD

**Issue by Carla-Moz** [mozilla/perfcompare#309]
Hi all, here are some essential tips for creating an issue to ask for help. It’s not enough to say, “[XYZ] doesn’t work. Help!” The more information you provide, the more likely others can help you solve your problem. :)

1. Please describe in detail the nature of the problem. What are you attempting to do? What are the steps you’ve taken already to solve the problem?
2. Include your dev environment – OS, version, etc. 
3. Write the steps to reproduce your error so others don’t have to figure it out themselves. 
4.  Describe the expected result and the actual results. It’s helpful if you post screenshots of error messages with arrows or pointers. However, I don’t suggest posting images of random code. Help others help you by guiding them and explaining what’s going on in the image.  
5.  Please ask either @kimberlythegeek or @Carla-Moz to add the “help wanted 🔥” label to your issue.
6. And don't forget to close your issue if the problem has been solved!

Thank you!

**Comment by Bahati308** [comment]
thanks a lot
