### ISSUE TITLE
Questions for issue #137  #help wanted

### ISSUE THREAD

**Issue by S1Y333** [mozilla/perfcompare#313]
Hi instructors, 

Can you please give us some clues about which array is the one we need to change? 
https://github.com/mozilla/perfcompare/issues/137

Also, if possible, can you please introduce briefly the logic of the whole project? That would be very helpful. Thanks so much!

<img width="370" alt="Screen Shot 2023-03-07 at 2 24 55 PM" src="https://user-images.githubusercontent.com/105386341/223530235-38a31057-391a-450c-8b58-59e680e910e5.png">

<img width="387" alt="Screen Shot 2023-03-07 at 2 24 20 PM" src="https://user-images.githubusercontent.com/105386341/223530049-1cd9fef2-3ce1-45f1-b8e7-8260400a958b.png">

_Originally posted by @S1Y333 in https://github.com/mozilla/perfcompare/issues/137#issuecomment-1458704188_

**Comment by S1Y333** [comment]
@Carla-Moz @kimberlythegeek Hi mentors, I did some research on this problem and found this information:https://redux.js.org/style-guide/#do-not-put-non-serializable-values-in-state-or-actions

Based on this rule, you should never put non-serializable objects in Redux. Can you please clarify what we need to revise? Thank you

**Comment by Carla-Moz** [comment]
Sorry for the delay. Yes, it's asking to refactor both arrays: checkedRevision, selectedRevisions. Along with the searchResults array in the SearchSlice reducer. Also, do you think you've done enough research to update these arrays to sets instead?
