### ISSUE TITLE
To make this website responsive ,designing it in a way that allows it to adapt to different screen sizes and devices.

### ISSUE THREAD

**Issue by vinayakjaas** [mozilla/perfcompare#314]
This is important because it ensures that your website is accessible and easy to use for all visitors, regardless of whether they are using a **desktop computer, a laptop, a tablet, or a smartphone.**
**Improved user experience**: Responsive design ensures that your website looks and works great on any device, providing a seamless user experience. This can help to keep visitors engaged and increase the chances of them returning to your site.
Cost-effective: Rather than creating multiple versions of your website for different devices, responsive design allows you to create a single website that works across all platforms. This can save you time and money in the long run.

**Comment by vinayakjaas** [comment]
I try to solve this issue so please go through it and give some suggestion how to improve it

**Comment by Formasitchijoh** [comment]
@vinayakjaas please can i work on this

**Comment by Gathu17** [comment]
I would also like to work on this

**Comment by deepeegee** [comment]
If there's no one assigned to this may I be assigned

**Comment by Hajihbola** [comment]
If there's no one assigned to this. Can I be assigned to work on it please?

**Comment by mafer23** [comment]
I can work on this @Carla-Moz

**Comment by cybraia** [comment]
hi @kimberlythegeek, I would like to know if this is resolved, else I will start working on it.

**Comment by vinayakjaas** [comment]
Hi @cybraia I Solved This Issue. So If you want You can review my code or start  working on some other Issue
