### ISSUE TITLE
displays the name of the element when the cursor is hovering over it:

### ISSUE THREAD

**Issue by vinayakjaas** [mozilla/perfcompare#325]
**Sometimes It is difficult to understand symbolic  representation so we display name what does it work it is easy to understand.**
**I Solved this Issue Already So please assign this task to Me.**
![2023-03-09 (21)](https://user-images.githubusercontent.com/96948435/223967522-6f44059f-0a99-44ad-9587-d323c4d1b75e.png)

**Comment by satyamksharma** [comment]
Hi there I would like to add this feature so please assign me
