### ISSUE TITLE
Alignment for table data is not consistent with the alignment of the table head in the results view

### ISSUE THREAD

**Issue by sumairq** [mozilla/perfcompare#327]
I think the data within the columns should have the same alignment as the heading to give it a more streamlined look.

![image](https://user-images.githubusercontent.com/60618877/223978726-f0390f93-8da7-48be-9965-65115cb824c9.png)

**Comment by sumairq** [comment]
Your feedback is highly appreciated 🙌

**Comment by tobidosumu** [comment]
Hello @Carla-Moz. I would like to resolve this issue. Thanks.

**Comment by tobidosumu** [comment]
@sumairq. Could you add some details (e.g. a link) about where to locate this issue in the view?

**Comment by sumairq** [comment]
Hi @tobidosumu You can locate this problem in the results view table. 

![Animation](https://user-images.githubusercontent.com/60618877/224350945-b3526dcf-6211-4b6b-b4e7-710a1a25cb02.gif)

**Comment by tobidosumu** [comment]
@sumairq I get it now. Thanks

**Comment by tobidosumu** [comment]
@Carla-Moz Hello @kimberlythegeek 
Hello. I have submitted a Pull Request to this issue.
