### ISSUE TITLE
web-app not fully responsive.

### ISSUE THREAD

**Issue by jakada01** [mozilla/perfcompare#329]
I am an outreachy applicant for the 2023 oureachy program. I have already started working on this issue. So i would like to be assigned to work on it.
![Not responsive](https://user-images.githubusercontent.com/73940440/224017743-348d56bb-150d-4764-8313-a7b0866473a8.PNG)

**Comment by satyamksharma** [comment]
Hi there, I waould like to work on this bug, please assign me

**Comment by mafer23** [comment]
I can work on this

**Comment by Sprof22** [comment]
I have already an innovative solution to this problem, by changing the UI to look pleasing to the user at mobile level. It should be looked into

**Comment by satyamksharma** [comment]
resolved this issue #329 and #355 and created a pr please check
