### ISSUE TITLE
make icons look "hoverable" #159

### ISSUE THREAD

**Issue by Trish-P** [mozilla/perfcompare#338]
I have cloned the repo and everything is working great but the task states that make any tooltip look hoverable. I don't seem to see a tooltip or can you point me in the right direction so I can complete this task,.
Or is it asking, anything that is hoverable, to add a tooltip?
<img width="600" alt="image" src="https://user-images.githubusercontent.com/115661325/224145539-853d6730-df72-46a9-83de-61148f8864bb.png">

**Comment by hkaur008** [comment]
Hi @Carla-Moz, Can I also work on this?
