### ISSUE TITLE
Results Bug

### ISSUE THREAD

**Issue by timmy3000** [mozilla/perfcompare#339]
Hi @kimberlythegeek,

My name is Hatim Matsue and i am Outreachy participant.

After comparing the items i navigated back (on my browser) and removed all items, When i navigate forward (on my browser) the results are rendered without the compared items.

![screencapture-localhost-3000-2023-03-09-22_07_50](https://user-images.githubusercontent.com/66499629/224150878-bdbf2698-91e0-4517-a44b-6912a3903f0c.png)

And with some comparisons the results are rendered with 'No results found' box at the bottom.

![screencapture-localhost-3000-2023-03-09-22_36_14](https://user-images.githubusercontent.com/66499629/224151072-07229150-dc38-4929-8088-60a8c12e4c32.png)

May i please work on these issues?

Thank you.

**Comment by hkaur008** [comment]
Hi @Carla-Moz, Can I also work on this?

**Comment by oburasamuel** [comment]
Is the bug already fixed
