### ISSUE TITLE
Responsiveness of search bar in compare results page

### ISSUE THREAD

**Issue by cybraia** [mozilla/perfcompare#361]
When 2 revisions are compared, in the compare results page, the following happens.
When clicked on edit button, the search bar is overflowing as shown below. 
<img width="193" alt="image" src="https://user-images.githubusercontent.com/66839875/224504939-5ed879c8-851a-4085-8b5a-e6e7f3efcaa2.png">
I would like to fix this issue. Please assign it to me @kimberlythegeek @Carla-Moz 
Thanks! I will start working on it right away.

**Comment by MuhamamdShehzad** [comment]
@kimberlythegeek @Carla-Moz I would also like to work on it. Please assign it to me.

**Comment by vinayakjaas** [comment]
Hii @kimberlythegeek  @Carla-Moz  Please Assign This Task To Me I am Happy To tackle This Issue

**Comment by vinayakjaas** [comment]
Hii @kimberlythegeek  @Carla-Moz  Please Assign This Task To Me I am Happy To tackle This Issue

**Comment by Businge931** [comment]
Hi @kimberlythegeek I would like to work on this issue

**Comment by priyasarpate** [comment]
@kimberlythegeek @Carla-Moz I would also like to work on this.
