### ISSUE TITLE
[🚀 Feature Request] Implement an unobtrusive 'scroll to top' button for results view

### ISSUE THREAD

**Issue by sumairq** [mozilla/perfcompare#370]
# **🚀 Feature Request**

## **Problem Statement 🤔**
* A user scrolling down the results view table becomes frustrated when they want to go back to the top for any number of reasons (they might want to filter results etc) for which they have to scroll all the way back to the top. It can become very cumbersome. For example: 

![scroll2](https://user-images.githubusercontent.com/60618877/224617458-04e35dc7-f5da-4135-bf1c-460903f7a233.gif)

* This becomes a headache when we have 100s of results to scroll.

---

## **Solution 💡**

* A button should be implemented, that takes the user to the top of the page eliminating the need for endless scrolling.
* This button has to integrate well with the rest of the page and not hide the contents of the table.
* It should hide when the user is at the top of the page.
* It should remain fixed to the screen while scrolling.
* It needs to have a tooltip, making it accessible for general usage as well as screen readers.

**Comment by tobidosumu** [comment]
Hello @sumairq.
I would like to work on this too if you don't mind.

**Comment by sumairq** [comment]
Please share your ideas about the positioning, size, colours and functionality of the 'scroll to top' button so we all have great ideas to work with. 👍

**Comment by sumairq** [comment]
@tobidosumu Here is somthing I have in mind.
A button in the bottom right corner that can be
- Clicked
- Hovered (Tooltip should appear)
- Button disappears when the user is at the top of the page.

Concept for a 'scroll to top' button at the bottom right             
:-------------------------:
![image](https://user-images.githubusercontent.com/60618877/224658441-2434b48f-9ddd-4659-9329-44c0d252bb67.png)

**Comment by tobidosumu** [comment]
I think the position of the **scroll-to-top** button is good as it follows popular convention and industry standards.

**Comment by sumairq** [comment]
@tobidosumu I agree 👍

**Comment by tobidosumu** [comment]
@sumairq What do you think about this design for the **scroll-to-top button**?
![proposedScrollToTopBtn](https://user-images.githubusercontent.com/60399800/224692894-993774cd-4a39-4c37-bfb4-eebc69cb924b.png)

**Comment by sumairq** [comment]
Here is the Figma design 🌟 
https://www.figma.com/file/ICd0TZSSdaqitTeNVD0M5N/Scroll-To-Top-Feature?node-id=0%3A1&t=LfBCstco0f3eP9VP-1

Figma Design ⭐           
:-------------------------:
![image](https://user-images.githubusercontent.com/60618877/224695345-f1b05927-813b-4e03-aa9a-c2ccbff44ca0.png)

What do you think @tobidosumu  @kimberlythegeek @Carla-Moz ?

**Comment by tobidosumu** [comment]
@sumairq I think adding design elements - in this case, color - from the Mozilla ecosystem is a brilliant idea as it ensures brand consistency across Mozilla products.

**Comment by tobidosumu** [comment]
@sumairq 
As regards the use of full arrow, I think it is fine. But when it comes to deciding what type of arrow to use for a scroll-to-top button, I often tend to go for a caret icon 😊. In my opinion, I think using a caret over a full arrow is consistent with the goal of adding an aura of minimalism to the design. And I think this is consistent with the minimalist feel that the design already has. But in the end, it's just my opinion. 😊

**Comment by tobidosumu** [comment]
@sumairq 
Here's an illustration of what I think the **scroll-to-top** button should look like and behave on the following states: 

**- normal**
**- hover**
**- active**

**Why I chose a white background**

-    Since the actual background color of the page is white, I thought it would be much better to use a white background color instead of grey background color. I think this will help in a better analysis of how the colors ( i.e. background color and caret color) of the scroll-to-top button interract with the background color of the page.

   
**Why I chose the colors**

-    Like you @sumairq, I also thought it was important to ensure brand consistency. That was why I used a blue color for the caret icon. Though I thought of using a very light hue of grey for the hover and active states, I considered your implementation of some of Mozilla brand colors and then decided to use the following hexadecimal color codes:

- `#0065FF ` Royal Blue for **hover state**

- `#1F3DB0` Navy blue or dark blue for **hover state**

- `#2D0F65` Dark purple for **active state**

**Why I added drop shadows:**

- Besides the fact that it is becoming a best practice to add drop shadow to an element such as a scroll-to-top button, drop shadow also helps to convey a sense of depth thereby adding to the effective communication of the design.

You can check out the design here 👉 https://www.figma.com/file/M725FrremrMXHe9FEUkFno/Scroll-to-top-button---PerfCompare?node-id=0%3A1&t=CpPlYYBEzWdnokde-1

Let me know what you think 🙏

![Scroll-to-top-button-perfCompare](https://user-images.githubusercontent.com/60399800/224705521-7c3d3166-a72e-443c-bca5-d65ae872e7b5.png)

@Carla-Moz and @kimberlythegeek could you let us know what you think about our design ideas, please? 🙏

**Comment by sumairq** [comment]
@tobidosumu As a matter of fact, it looks great. You have done a great job on contributing to the design. I love the colors, dropshadow. I missed the active state.
 Which is very important as: 
 - Adding an active state to a button is a simple but effective way to improve the usability and accessibility of the application. 
- It provides visual feedback to the user, indicates the current state of the button, and improves the overall user experience.

I am in favor of the caret icon, however It might be a bit confusing to the users as the confidence column has similar caret icons for showing low and high confidence as data. 

Figma Design             |  Your Design
:-------------------------:|:-------------------------:
![image](https://user-images.githubusercontent.com/60618877/224759651-3965daab-766a-4591-9359-0fc2efd7ec52.png)  |  ![image](https://user-images.githubusercontent.com/60618877/224759805-ddc4f9f5-c0a8-4a3e-b04e-e50befac4d50.png)

What do you think?

**Comment by sumairq** [comment]
@Businge931 I am working on it, please feel free to contribute. 🙌

**Comment by tobidosumu** [comment]
@sumairq I think you have valid point there. The thought of a user mistaking the caret up icon did cross my mind which was why I changed the backgound color of the scroll-to-top button from white to blue (for the hover state) and then made the caret icon itself white. The goal was with that was to create some contrast between the `confidence caret down` icon and `srcoll-to-top caret up` icon.  
But then, I am open to adopting your perference for a full arrow icon if that will help improve the User Experience (UX).

**Comment by sumairq** [comment]
@tobidosumu  I have created the button with these features: 

- I have added a little animation to the arrow itself. So that its purpose becomes immediately evident to the users. 
- On hover it shows an MUI tooltip explaining its purpose.
- Used the color scheme proposed by @tobidosumu.
- The button dissapears at the top.
- Has three states **Normal** **Hover** **Active**

Concept for a 'scroll to top' button at the bottom right             
:-------------------------:
![scroll3](https://user-images.githubusercontent.com/60618877/224777351-92285e3b-06e0-4480-a95f-0e8a314863c3.gif)

**Comment by tobidosumu** [comment]
@sumairq 
This is awesome 🙌. 
I love the fact that the scroll-to-top button is positioned outside of the table contents. 

As for the animation, while it looks nice by itself, in my opinion, I think it's kinda distracting. 
I feel it attracts too much attention than is necessary. Bear in mind that the essence of the page is not the scroll-to-top button, rather it's about the contents of the table. 

Overall, I think this is cool 😍.

**Comment by sumairq** [comment]
@tobidosumu 
That's a valid point . 
The animation can be a little distracting but on the positive side it has potential to add a bit of liveliness and interactiveness to the overall basic page while remaining in a corner of the screen.

What do you think ?

**Comment by tobidosumu** [comment]
@sumairq
Sure, a moderate use of animation/visual feedback can be effective in coordinating User Experience (UX). But I'm not quite sure what the right preference for PerfCompare would be in this case unless we research other Mozilla products that have a scroll-to-top button.

By and large, if we are subscribing to minimalist design principles, then I think this should also be reflected in how much animation/visual feedback we implement on the scroll-to-top button.

**Comment by sumairq** [comment]
I think @Carla-Moz @kimberlythegeek @beatrice-acasandrei can help us here. 🙌

**Comment by Prudence-Levison** [comment]
Nice discussion. I really had fun reading your discussions. I would like to propose that  the same arrow that leads up to the top of the page should also be a “top to bottom “ scroll when it gets to the top of the page 

I think this would help for better user experience, enabling the user to get to the bottom of the page without scrolling.

@sumairq  @tobidosumu  .. what do you both think ?

**Comment by tobidosumu** [comment]
@Prudence-Levison
Sure, not a bad idea at all. 
What do you think @sumairq and @Businge931?

**Comment by Businge931** [comment]
I think the button should be tied to one role, either to scroll to the very bottom of the list or to the top. If the user wants to scroll a small distance I think their mouse would be more convinient.

**Comment by tobidosumu** [comment]
@Businge931 
I see your perspective.
But I think giving the user multiple ways to accomplish scroll isn't a bad idea.
For instance, the user might want to scroll down to the bottom of the page right from the top at some point. 
At such point, @Prudence-Levison's idea becomes useful.  
At some other instance, the user may want to scroll down a bit. In such instance, the user may choose to use the scrollbar or simply swipe down.

**Comment by sumairq** [comment]
@Prudence-Levison In every instance you only see a 'scroll to top' button not a 'scroll to bottom' button. The 'scroll to bottom' does not have much utility, most users are scrolling down while scanning the results going top to bottom, in other words they don't want to miss anything. When they are done looking for the information they need, the most often requirement for them is to jump back to the top of the page.  

- Its not possible to make the same button perform both the tasks, taking the user to top as well as bottom. At any point between top and the bottom of the page, it will be impossible to decide whether the button should take the user to the top or bottom.

### However 🤔 

- The way it could work is if this functionality gets enabled only when the user is at the absolute top of the page and in all other scroll positions the 'scroll to bottom' cannot not exist because then the 'scroll to top' takes priority.

**Comment by Formasitchijoh** [comment]
Hello guys i missed this wonderfull discussion, but the ideas and contributions are great

@tobidosumu  i  appreciate the fact that you took interest and focused on the [Affirdance and signifiers] of your component its incredible and i think with that you might be able to reference this issue by @kimberlythegeek 
make icons look "hoverable" #159
