### ISSUE TITLE
Display revisions list upon selecting from dropdown

### ISSUE THREAD

**Issue by Formasitchijoh** [mozilla/perfcompare#372]
Having to focus on the input field before the revision list is displayed is a bit disturbing at time for most users .I propose the list should be displayed immediate the user selects the appropriate version from the drop down

**Comment by Formasitchijoh** [comment]
@Carla-Moz  @kimberlythegeek  i would like to work on this please

**Comment by Businge931** [comment]
@Carla-Moz and @kimberlythegeek I would like to work on this as well

**Comment by Formasitchijoh** [comment]
@Businge931  we could work on it if you dont mind ,

**Comment by Businge931** [comment]
Yes I agree. Lets wait for us to be assigned to it

**Comment by Formasitchijoh** [comment]
We really dont have to wait to be assigned we just have to work on it then
 submit a PR and wait for it to be approved

**Comment by Businge931** [comment]
Great then let's start on this ASAP!

**Comment by Businge931** [comment]
Have you done something yet?

**Comment by Formasitchijoh** [comment]
I am current ly working on it i could share with you my idea

**Comment by Businge931** [comment]
Can we create a room and discuss it more in detail

**Comment by Formasitchijoh** [comment]
that will be great

**Comment by Businge931** [comment]
What platform do you suggest, Slack?

**Comment by Formasitchijoh** [comment]
I surgest it be done here so others can learn and also share their ideas. What do you think

**Comment by Businge931** [comment]
Okay great.  So shall we merge our code

**Comment by Formasitchijoh** [comment]
have you done something yet

**Comment by Formasitchijoh** [comment]
Becauses like the mentors said more than one person can work on an issue, then they should indicate on the issue to the appropriate mentor. so i think that wont be a problem

**Comment by Businge931** [comment]
Okay great

**Comment by Businge931** [comment]
@Formasitchijoh Am gonna submit my idea also

**Comment by Businge931** [comment]
@Formasitchijoh how did you create a PR?

**Comment by Formasitchijoh** [comment]
> 

No problem @Businge931  we need more ideas onsolving the problem
