### ISSUE TITLE
Feature Request: Implement a Sticky Table Header for Improved User Experience While Studying Table Data

### ISSUE THREAD

**Issue by tobidosumu** [mozilla/perfcompare#374]
### Issue Summary
As a user of PerfCompare, I observed it is difficult to keep track of the column headers as I scrolled down the table. 
I am quite sure other users feel the same.
Therefore, I am requesting the implementation of a sticky table header that remains visible at the top of the table as a user scrolls down.
I believe this feature will help a user keep track of the column(s) they are analyzing without having to scroll back and forth to the top every now and then.
As it is right now, keeping track of the table data is cumbersome.

### Present User Experience (UX)
![need-for-a-stick-to-top-header-on-page-scroll-down](https://user-images.githubusercontent.com/60399800/224801957-3a008698-e570-4959-85ac-a5b1fc29022e.gif)

### Proposed User Experience (UX)
When a user scrolls down the table, the column headers should remain visible at the top of the table, providing a reference for the data they are viewing.

![proposed-design-solution-for-a-stick-to-top-header-on-page-scroll-down](https://user-images.githubusercontent.com/60399800/224802366-2f1fbc72-bec6-4d16-9618-798037dd271a.gif)

### Additional context
I believe that this feature would greatly improve the user experience for studying the several rows of data on the PerfCompare table. Other applications and websites have already implemented similar features, and I believe it would be a valuable addition to PerfCompare.

### Comments
I am open to discussing the feasibility and timeline for implementing this feature, and I would appreciate any feedback.

@kimberlythegeek @Carla-Moz kindly assign this task to me  🙏

**Comment by Prudence-Levison** [comment]
Nice one @tobidosumu 
Implementing the sticky header would improve the user’s experience of knowing which column they are staring at . 

Also, this is a great accessibility feature in the sense that people who can’t easily differentiate between a row and a column look at the sticky header and know which is which .

**Comment by tobidosumu** [comment]
@Prudence-Levison 
What do you think: should the **PerfCompare** header text be sticky with the table header or should it scroll with the page?

**Comment by Prudence-Levison** [comment]
@tobidosumu 
I think the PerfCompare header should be sticky with the table header. 

This would improve the aesthetic of the site as well as be more user-friendly.

**Comment by tobidosumu** [comment]
@Prudence-Levison 
I appreciate your feedback. Thanks 🙌

**Comment by Prudence-Levison** [comment]
Me too. 

I would like to work with you on this . 
@Carla-Moz ,  kindly assign me to this too

**Comment by tobidosumu** [comment]
@Prudence-Levison 
That would be nice! Welcome onboard buddy 🙌

**Comment by Businge931** [comment]
This is actually a great idea. UX should always be first priority, I would also want to join this team

**Comment by tobidosumu** [comment]
@Businge931 
Lovely! Welcome onboard mate  🙌

**Comment by Formasitchijoh** [comment]
This is great guys

**Comment by tobidosumu** [comment]
@sumairq @Formasitchijoh @Businge931 @Prudence-Levison

What do you guys think we can remove from or add to the sticky headers to further improve the UX?
Do you think adding an inner drop down shadow to the header would help achieve this?

**Comment by tobidosumu** [comment]
@sumairq @Formasitchijoh @Businge931 @Prudence-Levison

Hello guys.
What do you think can be done to fix this issue:

- Should there be a div/component with a white background color wrapping the **FeedbackAlert** and **ToggleDarkModeButton** icons? 

- Should **the two icons** be made to scroll along with the rest of the page?

- Should the two icons be moved down (vertically) into the PerCompare header component's section? 

- Please, feel free to come up with other ideas  🙏

![stickyHeaderDisplay-demo](https://user-images.githubusercontent.com/60399800/226096828-7704c798-4539-42be-b67a-9d6733b42b4e.gif)

**Comment by sumairq** [comment]
@tobidosumu I like your idea, however I think the header component should stay in place as before because it seems to consume alot of view height. This view height would be better utilized in showing the content of the table. 

- At mobile width, It could be implemented, so that the overall layout would mimic a mobile app at mobile width but we have to make sure that the sticky header is elegent and does not consume alot of view height.

**Comment by tobidosumu** [comment]
Thanks @sumairq for your brilliant contribution.

Just to be clear:
Are you saying the **PerfCompare header** should be made to scroll along with the rest of the page as before?

**Comment by sumairq** [comment]
@tobidosumu Yes, I say that primarily because the PerfCompare header itself is not functional or useful to the users while consuming valuable vertical space on the screen when they are scrolling. At best it can serve as a link to the homepage so yes in my opinion it should be made to scroll along with the rest of the page as before.

What do you think ?

**Comment by tobidosumu** [comment]
I think that makes a lot of sense! 🙌

**Comment by sumairq** [comment]
As a general rule, we should only use sticky header for functionality which is useful to the users while they are scrolling. 

If we take **example** of social networking sites like **Facebook** and **Twitter**, the users often update their statuses, publish tweets or read messages while they are scrolling down to browse their newsfeeds.

**Comment by tobidosumu** [comment]
You're right 💯

What do you think about the two icons, should they also scroll with the rest of the page?

**Comment by sumairq** [comment]
In my personal opinion only the table header in the results view page should be made into a sticky header. As the user might want to change the filters while they are scrolling. The idea is to keep it minimal because there is alot of room to make errors while creating a sticky header. 


![image](https://user-images.githubusercontent.com/60618877/226102264-6b1bda08-3a98-4c66-9bab-567a7906d35a.png)
