### ISSUE TITLE
Feature request: an eslint plugin that spots issues with accessibility of the app

### ISSUE THREAD

**Issue by sabbCodes** [mozilla/perfcompare#386]
I'm suggesting we add an eslint plugin that spots accessibility issues with the application from the development phase.

**Comment by julienw** [comment]
Some pointers:
* [eslint-plugin-jsx-a11y](https://www.npmjs.com/package/eslint-plugin-jsx-a11y)
* [@axe-core/react](https://www.npmjs.com/package/@axe-core/react)
* [jest-axe](https://github.com/nickcolley/jest-axe)
* [axe devtool](https://www.deque.com/axe/) (look near the bottom of the page for the firefox extension)

**Comment by Formasitchijoh** [comment]
Hello @julienw  could i work with @sabbCodes  on this feature please

**Comment by sabbCodes** [comment]
Hi @julienw 
I've added the eslint-plugin-jsx-a11y plugin.
Here's the PR:
https://github.com/mozilla/perfcompare/pull/392

I'd like to explore the @axe-core/react too.
