### ISSUE TITLE
Improve UX design for the search results list 

### ISSUE THREAD

**Issue by Gathu17** [mozilla/perfcompare#394]
I noticed that the search result list had poor user experience where the content overflowed the screen and one had to click inside in order to navigate through the list as seen below. This issue is meant to improve the responsiveness in different screen sizes with better design for scrolling.  
![Screenshot (2150)](https://user-images.githubusercontent.com/92152669/225887552-61d99f27-aa0d-48bb-89dc-d5522f4719a1.png)

**Comment by Hajihbola** [comment]
Good day, please I would love to work on this project but I have been finding it difficult to locate the part where this table data was input in the code base. I have spent over 2-3hours locating where the table data code is in the code base.
I don't mind getting help in locating the file.
Thanks

**Comment by Hajihbola** [comment]
> It is located in the SearchResultList.tsx file in Search folder. In there you'll find a material UI Box components where you can add your styling

Thank you. I will get on it.

**Comment by Hajihbola** [comment]
I have worked on it and I am on the PR stage.
Can I have this issue assigned to me please?
@kimberlythegeek @Carla-Moz @Gathu17 
Thank you.

**Comment by Hajihbola** [comment]
Please, I have been getting the code to pass the tests while doing a PR on GitHub but I give getting a "2 snapshot failed" feedback.
I don't mind getting help as regards that. I'm stuck on making my contribution pass the test even after I have ran the "npm run lint:fix" and "npm run test -- -u" on my terminal.
Thank you.

**Comment by Hajihbola** [comment]
I have been able to have it solved.
Can I have it assigned to me please?
@Gathu17 @kimberlythegeek @Carla-Moz
