### ISSUE TITLE
Increase contrast beteen 'Github Repo' link and its background to make it accessible to users with limited sight [Accessibility ⭐ ]

### ISSUE THREAD

**Issue by sumairq** [mozilla/perfcompare#399]
According to the [Wave](https://wave.webaim.org/) evaluation tool the contrast between the Github Repo link and it's background is not sufficient. It needs to be fixed.

![image](https://user-images.githubusercontent.com/60618877/226098232-d35da42e-612b-4aa4-9fc5-6caf02b6ce06.png)

**Comment by siddhi-244** [comment]
Can i work on this ? I am a outreachy participant
