### ISSUE TITLE
[Improve UI 🎨] - Jerkiness on Display of SearchResultsList

### ISSUE THREAD

**Issue by tobidosumu** [mozilla/perfcompare#421]
### Description

When the SearchInput component is clicked, the SearchResultsList component is displayed. However, there is a slight jerkiness when the component is displayed, as a vertical scrollbar appears. This makes the UI feel less smooth and polished, thus affecting the overall user experience of the PerfCompare web app.

### Steps to Reproduce

- Click on the SearchInput component.

- Observe the display of the SearchResultsList component.

### Expected Result

The SearchResultsList component should be displayed smoothly without any jerkiness or vertical scrollbar.

### Actual Result

The SearchResultsList component is displayed with a slight jerkiness, and a vertical scrollbar appears.
![searchDropDownWidth-before](https://user-images.githubusercontent.com/60399800/226217520-553e78c9-e0f1-4163-a2e5-011152ec26ca.gif)

This issue affects the overall user experience of the application and should be addressed as soon as possible.

@Carla-Moz @kimberlythegeek

**Comment by Gathu17** [comment]
#394
