### ISSUE TITLE
Scrollable Search Results List

### ISSUE THREAD

**Issue by timmy3000** [mozilla/perfcompare#435]
Hi @kimberlythegeek,

May i please make the Search Results List Scrollable so that the search input can be more accessable?

Thank you.

![screen-capture](https://user-images.githubusercontent.com/66499629/226742197-a23ef591-4a1e-4c5a-af08-8485d29df61c.gif)

**Comment by tobidosumu** [comment]
@timmy3000 @kimberlythegeek @Carla-Moz 

Hello.
This issue was raised in #421 and a PR to fix it was made in #422.

**Comment by timmy3000** [comment]
@tobidosumu Sorry, I was not aware that your issue was for solving the same problem; Thanks for the heads-up.

**Comment by tobidosumu** [comment]
No problem @timmy3000 

I was only trying to prevent the replication of the same issue.

Please, feel free to make as many PRs to the issues as you deem necessary. I believe this will give the Maintainers the opportunity to merge the best PRs to the issues raised. 

And please be reminded that the overall goal with this project is to create the best product possible for the users.
