### ISSUE TITLE
Make `Compare with Base` more accessible and write tests for the improvements

### ISSUE THREAD

**Issue by sumairq** [mozilla/perfcompare#486]
Make `Compare with base` in the `Search view` accessible through keyboard while making the interface more intuitive for screen reader users.

The regimen for improvements to accessibility in this case could be:

- Add a hidden "Skip to content" link.
- Work on improving the tab index and check improvements with manual testing.
- Enable announcement of live regions to screen reader users.
- Work on visible focus styles.
- Make sure that if we are opening a layer on screen we are actually trapping the focus within the top layer.
- Write tests for accessibility.

**Comment by julienw** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1855187

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
