### ISSUE TITLE
Add Home link button with arrow left on Results View Page

### ISSUE THREAD

**Issue by Carla-Moz** [mozilla/perfcompare#508]
We currently don't have a home button in the Results View page that allows the user to navigate back to the home page.

See ''Content Help" in the image below. 

<img width="893" alt="Screenshot 2023-07-27 at 14 10 21" src="https://github.com/mozilla/perfcompare/assets/88336547/31b2d958-71ef-46a4-8cda-290ccac7f10e">

**Comment by beatrice-acasandrei** [comment]
This issue is fulfilling https://bugzilla.mozilla.org/show_bug.cgi?id=1846020.
