### ISSUE TITLE
"Search by title" cannot be interacted with

### ISSUE THREAD

**Issue by gregtatum** [mozilla/perfcompare#524]
<img width="426" alt="Image of the search by title field" src="https://github.com/mozilla/perfcompare/assets/1588648/358dde5f-f6ac-4067-9c9b-4cd8fa7ad7e2">

I try clicking on it, and it doesn't get focus. I also try to tab to it via keyboard and it won't get focus.

**Comment by gregtatum** [comment]
Example URL: https://perf.compare/#/compare-results?revs=8f6fc7ceb216087fe30ee43fc71290e059e09609,1569bb99544c2d0b64b3ed8d465f033f8359b9d1&repos=try,try&framework=13

**Comment by julienw** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1855184

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
