### ISSUE TITLE
Job dropdown is cut off

### ISSUE THREAD

**Issue by gregtatum** [mozilla/perfcompare#525]
<img width="948" alt="Screenshot of the perf compare homepage" src="https://github.com/mozilla/perfcompare/assets/1588648/aa0a4cd8-6c0f-43e3-bcc0-54e541b66cd2">

The job dropdown is cut off by its containing element.

**Comment by julienw** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1855185

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
