### ISSUE TITLE
Rows do not show if "lower" or "higher" metrics are better

### ISSUE THREAD

**Issue by gregtatum** [mozilla/perfcompare#526]
<img width="925" alt="Screenshot of the rows on a perf.compare screen" src="https://github.com/mozilla/perfcompare/assets/1588648/b1265e50-79a3-48d3-aefc-4b593995adef">

[Example run](https://perf.compare/#/compare-results?revs=1569bb99544c2d0b64b3ed8d465f033f8359b9d1,8f6fc7ceb216087fe30ee43fc71290e059e09609&repos=try,try&framework=1)

This information should be in the job details, and if you have a regression, it's hard to understand which number is the better number.

In the job details view I implemented a table a few years back that included this information, and I have found it really useful to know this.

<img width="971" alt="Screenshot of the table from the link below" src="https://github.com/mozilla/perfcompare/assets/1588648/678e2722-03cf-41c5-a923-a1d71d1bd090">

[This can be seen here.](https://treeherder.mozilla.org/jobs?repo=try&group_state=expanded&revision=8f6fc7ceb216087fe30ee43fc71290e059e09609&selectedTaskRun=BNvxQVwpSiGSsBY4lbESDA.0)

**Comment by julienw** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1855186

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
