### ISSUE TITLE
Consider providing visual clues to regressors

### ISSUE THREAD

**Issue by gregtatum** [mozilla/perfcompare#527]
When scanning a row of results it would be nice to know which are the regressing stats visually. For instance a simple mock-up could be something like this:

<img width="943" alt="image" src="https://github.com/mozilla/perfcompare/assets/1588648/1e769d1d-eb88-410a-a056-20a0d333d6ce">

Then on hover it could have a title of something like "This stat is worse", or something phrased nicer than that.

**Comment by julienw** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1855188

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
