### ISSUE TITLE
Automatically determine the testing framework

### ISSUE THREAD

**Issue by gregtatum** [mozilla/perfcompare#528]
When I regress a perf test, it's usually a specific one. I will then kick off a few runs with a baseline on a known revision, and some with my fixes. When selecting the jobs in perf.compare it takes some cognitive overhead to figure out what suite the test I care about is from. It would be nice when selecting a job, the job would be loaded and inspected by the code to determine which test suites were run. It would then automatically pick (or filter) the "Framework" dropdown.

**Comment by julienw** [comment]
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1852296

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).
