### ISSUE TITLE
ensure API calls do not contain malicious values

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/perfcompare#74]
Feedback from @julienw :

> I think you should either use encodeURIComponent or the URLSearchParams object to make sure this search value isn't malicious.
> 
> Also not sure where treeherderBaseURL and repository come from, but you might need to use encodeURIComponent for them too, if they come from some untrusted place.
> 
> These are probably not a very big deal in this case because this is just a get operation, but better do it to be safe :)
> 
> Obviously the same comment applies to the other fetch commands.

**Comment by Dpreshy** [comment]
hello mentor kimberly, can i be assigned to this

**Comment by Sprof22** [comment]
Can I have this assigned to me @mayangiaretha  @kimberlythegeek
