### ISSUE TITLE
Display Local Time Zones for Revisions in Search Results and Selected Revisions

### ISSUE THREAD

**Issue by Carla-Moz** [mozilla/perfcompare#767]
**Description:**  
Display the local time zones of revisions in both the search results and the selected revision

**Steps to Reproduce:**

1. Read the [PerfCompare Documentation](https://docs.google.com/document/d/1cpQEZXw0M5QjmNL2F1S9NKjWmz6A9Ks7zELVNTXLeB4/edit#heading=h.u62ha0d6mpxl) to get familiar with the app.
2. Navigate to the home page: https://perf.compare/ 
3. Click on any search input
4. Observe that the time zones are not included in the revisions
![image](https://github.com/user-attachments/assets/bc2b4abe-f36d-41b2-9f2b-7ad6023cb008)
5. Observe the time zones are not included in the selected revision
![image](https://github.com/user-attachments/assets/95b99d54-aab3-4775-9842-b9f9e5ac7223)

**Acceptance Criteria:**
1. Display the local time zone alongside each revision timestamp in the search results.
2. Ensure the local time zone is also displayed for any selected revision.
3. The time zone should be correctly formatted and easy to read.

![image](https://github.com/user-attachments/assets/c1fc96b1-09ae-458c-8a61-5c0d11cd66e7)

**Comment by hibaa03** [comment]
working on this

**Comment by osujipius** [comment]
@Carla-Moz When you say "Add the UTC timestamp on hover through a tooltip" where should the tooltip be placed? The selected revision or the search result?

**Comment by Carla-Moz** [comment]
@osujipius When the user hovers over the time, the tooltip can be above the selected revision or the revision in the search results.
